### PR TITLE
Add lines shuffling and number of files in configuration and check document integrity

### PR DESCRIPTION
**Pull request by Aazhar**

### CODE REVIEW

**Comment by Aazhar** [comment]
poke @kermitt2 , can you review this ?

**Comment by kermitt2** [comment]
thanks @Aazhar !!
Shouldn't the number of documents to be downloaded be a command line parameter rather than a config parameter? It's something by nature dynamic that would change a lot.

**Comment by Aazhar** [comment]
Ah yes correct, I'll pull a new request

**Comment by Aazhar** [comment]
@kermitt2 now the size could be set from the command line, I have also added document check using pdftotext.

**Comment by kermitt2** [comment]
I have implemented it a bit differently, in a way that is simpler (no use of numpy weaponry and shuffle) and more accurate I think (it is considering the actual total number of entries when randomizing). 

Harvesting sample remains a non default option too - this should not be the default usage. 

I would also leave the check for PDF integrity outside this tool, as it might slow down the harvesting quite a lot and it is up to the user to decide what to do with the PDF.

**Comment by kermitt2** [comment]
the commit for the features corresponding to this PR is 3064cb85182cba97664f60ede285dba218713391
@Aazhar your feedback very welcomed !

**Comment by Aazhar** [comment]
Yes it looks fine too.

**Pull request closed without merging**
